# Generated by Django 5.2.12 on 2026-06-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoogleCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                (
                    "token_uri",
                    models.CharField(
                        default="https://oauth2.googleapis.com/token", max_length=200
                    ),
                ),
                ("client_id", models.CharField(max_length=300)),
                ("client_secret", models.CharField(max_length=300)),
                ("scopes", models.TextField()),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "target_calendar_id",
                    models.CharField(default="primary", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Google Credentials",
                "verbose_name_plural": "Google Credentials",
            },
        ),
    ]
