# Generated by Django 5.2.12 on 2026-06-23 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument", models.CharField(blank=True, max_length=100)),
                (
                    "focus",
                    models.CharField(
                        choices=[
                            ("technique", "Technique"),
                            ("repertoire", "Repertoire"),
                            ("sight_reading", "Sight Reading"),
                            ("theory", "Theory"),
                            ("improvisation", "Improvisation"),
                            ("free", "Free Practice"),
                        ],
                        default="free",
                        max_length=30,
                    ),
                ),
                (
                    "pieces",
                    models.TextField(
                        blank=True, help_text="Pieces / exercises to work on"
                    ),
                ),
                ("planned_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "plan_block",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_session",
                        to="schedule.planblock",
                    ),
                ),
                (
                    "template_block",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_session",
                        to="schedule.templateblock",
                    ),
                ),
            ],
        ),
    ]
