# Generated by Django 5.2.12 on 2026-06-23 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("base", "Base / Easy"),
                            ("tempo", "Tempo"),
                            ("intervals", "Intervals"),
                            ("long", "Long Run"),
                            ("recovery", "Recovery"),
                            ("race", "Race"),
                        ],
                        default="base",
                        max_length=20,
                    ),
                ),
                (
                    "planned_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "actual_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "planned_pace",
                    models.CharField(
                        blank=True, help_text="e.g. 5:30/km", max_length=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "plan_block",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_session",
                        to="schedule.planblock",
                    ),
                ),
                (
                    "template_block",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_session",
                        to="schedule.templateblock",
                    ),
                ),
            ],
        ),
    ]
