# Generated by Django 5.2.12 on 2026-06-23 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin_running", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("start_date", models.DateField(help_text="Monday of Week 1")),
                (
                    "pace_easy_sec",
                    models.IntegerField(default=360, help_text="6:00/km"),
                ),
                (
                    "pace_tempo_sec",
                    models.IntegerField(default=300, help_text="5:00/km"),
                ),
                (
                    "pace_interval_sec",
                    models.IntegerField(default=270, help_text="4:30/km"),
                ),
                (
                    "pace_long_sec",
                    models.IntegerField(default=390, help_text="6:30/km"),
                ),
                (
                    "pace_recovery_sec",
                    models.IntegerField(default=420, help_text="7:00/km"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="runsession",
            name="actual_pace",
            field=models.CharField(
                blank=True,
                help_text="e.g. 5:12/km — filled by Strava sync",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="runsession",
            name="strava_activity_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TrainingPlanWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("base", "Base"),
                            ("build", "Build"),
                            ("peak", "Peak"),
                            ("taper", "Taper"),
                            ("recovery", "Recovery"),
                        ],
                        default="base",
                        max_length=20,
                    ),
                ),
                ("target_km", models.DecimalField(decimal_places=1, max_digits=6)),
                ("notes", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="plugin_running.trainingplan",
                    ),
                ),
            ],
            options={
                "ordering": ["week_number"],
                "unique_together": {("plan", "week_number")},
            },
        ),
        migrations.CreateModel(
            name="TrainingPlanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("base", "Base / Easy"),
                            ("tempo", "Tempo"),
                            ("intervals", "Intervals"),
                            ("long", "Long Run"),
                            ("recovery", "Recovery"),
                            ("race", "Race"),
                        ],
                        default="base",
                        max_length=20,
                    ),
                ),
                ("target_km", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "plan_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="plugin_running.trainingplanweek",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week"],
            },
        ),
    ]
