# Generated by Django 5.2.12 on 2026-08-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin_running", "0002_trainingplan_runsession_actual_pace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="paused_on",
            field=models.DateField(
                blank=True,
                help_text="Set while paused (injury, illness). Resuming shifts start_date by the time off.",
                null=True,
            ),
        ),
    ]
