# Generated by Django 5.2.12 on 2026-06-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planweek",
            name="gcal_pending_delete_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
