# Generated by Django 5.2.12 on 2026-06-23 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("schedule", "0002_planweek_gcal_pending_delete_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "recurrence_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="How many times per week this should appear.",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_tasks",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="planblock",
            name="weekly_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_blocks",
                to="schedule.weeklytask",
            ),
        ),
    ]
