# Generated by Django 5.2.12 on 2026-06-26 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_add_weeklytask_planblock_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanWeekReflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planning_completed_at", models.DateTimeField(blank=True, null=True)),
                ("review_completed_at", models.DateTimeField(blank=True, null=True)),
                ("weekly_intention", models.TextField(blank=True)),
                ("top_priorities", models.TextField(blank=True)),
                ("wins", models.TextField(blank=True)),
                ("misses", models.TextField(blank=True)),
                ("lessons", models.TextField(blank=True)),
                ("next_week_notes", models.TextField(blank=True)),
                (
                    "energy_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "week",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflection",
                        to="schedule.planweek",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carried_goals",
                        to="schedule.weeklygoal",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="schedule.planweek",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
