# Generated by Django 5.2.12 on 2026-07-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_daily_recap_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycheckin",
            name="notes_for_tomorrow",
            field=models.TextField(blank=True),
        ),
    ]
