# Generated by Django 5.2.15 on 2026-10-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_dailycheckin_notes_for_tomorrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrainDumpItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_archived", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
