# Generated by Django 5.2.12 on 2026-07-30 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule", "0007_dailycheckin_notes_for_tomorrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_block",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_notes",
                        to="schedule.planblock",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "meeting notes",
            },
        ),
    ]
