# Generated by Django 5.2.12 on 2026-06-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StravaCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("athlete_id", models.BigIntegerField()),
                ("athlete_name", models.CharField(blank=True, max_length=200)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                (
                    "expires_at",
                    models.IntegerField(
                        help_text="Unix timestamp when access_token expires"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Strava Credentials",
                "verbose_name_plural": "Strava Credentials",
            },
        ),
    ]
